# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sihle Manqele - Personal Profile
email: sihle.manqele@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sihle Manqele's personal profile, featuring insights on AI, agriculture,
  and personal journey.

# For GitHub Pages project sites, if applicable (e.g., yourusername.github.io/sihle-profile)
# baseurl: "/sihle-profile" # the subpath of your site, e.g. /blog
# url: "https://yourusername.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima # Or your chosen theme
plugins:
  - jekyll-feed # If you use a blog feed

# Custom data for Campaigns tab
campaigns:
  - name: My GoFundMe
    url: https://gofundme.com/my-campaign-placeholder
    description: Support my new project in sustainable agriculture!
  - name: Patreon Support for Content Creation
    url: https://patreon.com/sihlemanq
    description: Become a patron for exclusive content and early access to my work.
  - name: Hemp Growers' Association Initiative
    url: https://imvunopatreon.github.io/imvunotech/
    description: Help establish a new association for hemp growers in Africa.

# Custom data for Content tab (YouTube links)
youtube_content:
  - title: "Introduction to African Agriculture"
    url: https://www.youtube.com/watch?v=youtube_video_id_1 # Replace with actual YouTube video ID
    description: A deep dive into the opportunities and challenges in African farming.
  - title: "AI in Smart Farming: A Beginner's Guide"
    url: https://www.youtube.com/watch?v=youtube_video_id_2 # Replace with actual YouTube video ID
    description: Understanding how Artificial Intelligence can revolutionize farming practices.
  - title: "Chess Strategies for Beginners"
    url: https://www.youtube.com/watch?v=youtube_video_id_3 # Replace with actual YouTube video ID
    description: My personal tips and tricks for new chess players.

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
